#Creacion tabla Usuarios
#Usuario de 20 caracteres máximo
#Contrasenia pasada por MD5 por lo que se usan los 32 caracteres
#Admin será una bandera controladora para poder distinguir el usuario que se
#registrará de Admin con los demás, siendo 0 un usuario normal y 1 para Admin.
CREATE TABLE IF NOT EXISTS `PRESTAMO_LIBROS`.`USUARIOS` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR UNICO DEL USUARIO',
    `USUARIO` VARCHAR(20) NOT NULL COMMENT 'NOMBRE DE USUARIO PARA EL LOGIN',
    `CONTRASENIA` CHAR(32) NOT NULL COMMENT 'CONTRASENIA DEL USUARIO PASADA POR MD5 PARA UN ALMACENAJE MAS SEGURO',
    `ADMIN` ENUM('0','1') NOT NULL DEFAULT '0' COMMENT 'BANDERA QUE PERMITE LA DIFERENCIACION DE PERMISOS, 1 PARA LOS ADMINISTRADORES, 0 PARA LOS USUARIOS COMUNES',
    PRIMARY KEY PK_USUARIOS_ID(`ID`),
    UNIQUE UN_USUARIOS_USUARIO(`USUARIO`)
) COMMENT 'TABLA PARA LA INFORMACION DE LOGIN DE LOS USUARIOS';

#Creacion tabla Alumnos
#Nombre de 45 caracteres máximo
#PApellido es para el primer apellido, 45 caracteres máximo
#SApellido es para el segundo apellido, 45 caracteres máximo
#Telefono 13 caracteres máximo, para telefonos 0442299120504 por ejemplo
#DNI es el documento nacional de identidad, formado normalmente por 8
#caracteres numericos y uno, al final, alfabetico
#IDUSUARIO es la llave foránea que relaciona ambas tablas
CREATE TABLE IF NOT EXISTS `PRESTAMO_LIBROS`.`ALUMNOS` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR UNICO DEL ALUMNO',
    `NOMBRE` VARCHAR(45) NOT NULL COMMENT 'NOMBRE DEL ALUMNO',
    `PAPELLIDO` VARCHAR(45) NOT NULL COMMENT 'PRIMER APELLIDO DEL ALUMNO',
    `SAPELLIDO` VARCHAR(45) NOT NULL COMMENT 'SEGUNDO APELLIDO DEL ALUMNO',
    `TELEFONO` VARCHAR(13) NOT NULL COMMENT 'TELEFONO DEL ALUMNO, DESDE NUMEROS COMO 123456789 HASTA 2291234567 O 0442291234567, SOLO NUMEROS',
    `DNI` CHAR(9) NOT NULL COMMENT 'DOCUMENTO NACIONAL DE IDENTIFICACION, FORMADO POR 8 NUMEROS Y UNA LETRA AL FINAL, POR EJEMPLO 12345678A',
    `IDUSUARIO` INT(11) COMMENT 'LLAVE FORANEA QUE HACE REFERENCIA AL ID DE UN REGISTRO DE LA TABLA USUARIOS', 
    PRIMARY KEY PK_ALUMNOS_ID(`ID`),
    UNIQUE UN_ALUMNOS_DNI(`DNI`),
    UNIQUE UN_ALUMNOS_IDUSUARIO(`IDUSUARIO`),
    FOREIGN KEY FK_ALUMNOS_IDUSUARIO(`IDUSUARIO`) REFERENCES `USUARIOS`(`ID`) ON DELETE CASCADE
) COMMENT 'TABLA PARA LA INFORMACION GENERAL DEL ALUMNO Y QUE LLEVA COMO MUESTRA DE SU RELACION CON USUARIO UNA LLAVE FORANEA PARA ELLO';

#Creacion tabla Libros
#Titulo de 180 caracteres máximo
#Autor de 90 caracteres máximo
#NumPaginas de 0 a 9999 páginas
#Estado se manejará con 0 y 1, como bandera para señalar si está disponible
#para ser tomado prestado por el alumno, 0 para ocupado y 1 para libre
#ISBN es una referencia unica de cada libro, formada por 13 caracteres numericos
#y guiones, pero se manejará sin su division de guiones, sólo números
CREATE TABLE IF NOT EXISTS `PRESTAMO_LIBROS`.`LIBROS` ( 
    `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR UNICO DE LOS LIBROS',
    `TITULO` VARCHAR(180) NOT NULL COMMENT 'TITULO DEL LIBRO',
    `AUTOR` VARCHAR(90) NOT NULL COMMENT 'AUTOR, NOMBRE Y APELLIDO, DEL LIBRO',
    `NUMPAGINAS` INT(4) NOT NULL COMMENT 'NUMERO DE PAGINAS DEL LIBRO, DE 1 A 9999',
    `ESTADO` ENUM('0','1') NOT NULL DEFAULT '1' COMMENT 'BANDERA PARA LA DIFERENCIACION DE LOS LIBROS OCUPADOS Y LOS LIBRES, 0 PARA LOS OCUPADOS, 1 PARA LOS LIBRES',
    `ISBN` CHAR(13) NOT NULL COMMENT 'ISBN DEL LIBRO, FORMADO UNICAMENTE POR NUMEROS, SIN INCLUIR GUIONES, FORMADO POR 13 O 10 DIGITOS',
    PRIMARY KEY PK_LIBROS_ID(`ID`), 
    UNIQUE UN_LIBROS_ISBN(`ISBN`)
) COMMENT 'TABLA PARA LA INFORMACION DE LOS LIBROS A SER PRESTADOS';

#Creacion tabla LIBROSDEUSUARIO
#IdAlumno llave foránea que hace referencia al ID de la tabla Alumnos
#IdLibro llave foránea que hace referencia al ID de la tabla Libros
CREATE TABLE IF NOT EXISTS `PRESTAMO_LIBROS`.`LIBROSDEALUMNO` ( 
    `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR UNICO DE LOS REGISTROS DE LA TABLA',
    `IDALUMNO` INT(11) NOT NULL COMMENT 'LLAVE FORANEA PARA LA REFERENCIA A UN REGISTRO DE LA TABLA ALUMNOS',
    `IDLIBRO` INT(11) NOT NULL COMMENT 'LLAVE FORANEA PARA LA REFERENCIA A UN REGISTRO DE LA TABLA LIBROS',
    PRIMARY KEY PK_LIBROSDEALUMNO_ID(`ID`),
    UNIQUE UN_LIBROSDEALUMNO_IDLIBRO(`IDLIBRO`),
    FOREIGN KEY FK_LIBROSDEALUMNO_IDALUMNO(`IDALUMNO`) REFERENCES `ALUMNOS`(`ID`),
    FOREIGN KEY FK_LIBROSDEALUMNO_IDLIBRO(`IDLIBRO`) REFERENCES `LIBROS`(`ID`) ON DELETE CASCADE
) COMMENT 'TABLA PARA LA INFORMACION DE LOS PRESTAMOS DE LIBROS, EL ALUMNO QUE TIENE EL LIBRO Y LOS LIBROS PRESTADOS';