USE `PRESTAMO_LIBROS`;

#Llenado de tabla ALUMNOS
INSERT INTO ALUMNOS A (A.NOMBRE, A.PAPELLIDO, A.SAPELLIDO, A.TELEFONO, A.DNI, A.IDUSUARIO) VALUES("Marco", "Lopez", "Barrera", "9242043", "12121212A", 1);
INSERT INTO ALUMNOS A (A.NOMBRE, A.PAPELLIDO, A.SAPELLIDO, A.TELEFONO, A.DNI, A.IDUSUARIO) VALUES("Jorge", "Hernandez", "Navarrete", "9242044", "12121212B", 2);
INSERT INTO ALUMNOS A (A.NOMBRE, A.PAPELLIDO, A.SAPELLIDO, A.TELEFONO, A.DNI, A.IDUSUARIO) VALUES("Ruben", "Garcia", "Malaga", "9242045", "12121212C", 3);
INSERT INTO ALUMNOS A (A.NOMBRE, A.PAPELLIDO, A.SAPELLIDO, A.TELEFONO, A.DNI, A.IDUSUARIO) VALUES("Ulises", "Ponce", "Avila", "9242046", "12121212D", 4);
INSERT INTO ALUMNOS A (A.NOMBRE, A.PAPELLIDO, A.SAPELLIDO, A.TELEFONO, A.DNI, A.IDUSUARIO) VALUES("Israel", "Marcial", "Parra", "9242047", "12121212E", 5);

#Llenado de tabla LIBROS
INSERT INTO LIBROS L (L.TITULO, L.AUTOR, L.NUMPAGINAS, L.ESTADO, L.ISBN) VALUES("Amores Perros", "Un mexicano", 100, '0', "1231231231231");
INSERT INTO LIBROS L (L.TITULO, L.AUTOR, L.NUMPAGINAS, L.ESTADO, L.ISBN) VALUES("Nacho Libre", "Otro mexicano", 200, '0', "1231231231232");
INSERT INTO LIBROS L (L.TITULO, L.AUTOR, L.NUMPAGINAS, L.ESTADO, L.ISBN) VALUES("Amarte Duele", "Un mexicano", 300, '0', "1231231231233");
INSERT INTO LIBROS L (L.TITULO, L.AUTOR, L.NUMPAGINAS, L.ESTADO, L.ISBN) VALUES("Me Gusta Pero Me asusta", "Otro mexicano", 1000, '0', "1231231231234");
INSERT INTO LIBROS L (L.TITULO, L.AUTOR, L.NUMPAGINAS, L.ESTADO, L.ISBN) VALUES("Toña La Negra", "Un mexicano", 50, '1', "1231231231235");

#Llenado de tabla USUARIOS
INSERT INTO USUARIOS U (U.USUARIO, U.CONTRASENIA) VALUES("marquito", MD5("12121234"));
INSERT INTO USUARIOS U (U.USUARIO, U.CONTRASENIA) VALUES("jorgito", MD5("12121234"));
INSERT INTO USUARIOS U (U.USUARIO, U.CONTRASENIA) VALUES("rubencito", MD5("12121234"));
INSERT INTO USUARIOS U (U.USUARIO, U.CONTRASENIA) VALUES("ulicito", MD5("12121234"));
INSERT INTO USUARIOS U (U.USUARIO, U.CONTRASENIA) VALUES("israelito", MD5("12121234"));
INSERT INTO USUARIOS U (U.USUARIO, U.CONTRASENIA, U.ADMIN) VALUES("admin", MD5("12121234"), '1');

#Llenado de tabla LIBROSDEALUMNO
INSERT INTO LIBROSDEALUMNO L (L.IDALUMNO, L.IDLIBRO) VALUES(1, 1);
INSERT INTO LIBROSDEALUMNO L (L.IDALUMNO, L.IDLIBRO) VALUES(2, 2);
INSERT INTO LIBROSDEALUMNO L (L.IDALUMNO, L.IDLIBRO) VALUES(3, 3);
INSERT INTO LIBROSDEALUMNO L (L.IDALUMNO, L.IDLIBRO) VALUES(3, 4);