#Creacion procedimiento delete ALUMNOS
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USP_ALUMNOS_D`(IN `IN_ID` INT)
DELETE FROM ALUMNOS WHERE ID = IN_ID$$
DELIMITER ;

#Creacion procedimiento delete LIBROS
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USP_LIBROS_D`(IN `IN_ID` INT)
DELETE FROM LIBROS WHERE ID = IN_ID$$
DELIMITER ;

#Creacion procedimiento delete LIBROSDEALUMNO
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USP_LIBROSDEALUMNO_D`(IN `IN_ID` INT)
DELETE FROM LIBROSDEALUMNO WHERE ID = IN_ID$$
DELIMITER ;

#Creacion procedimiento delete USUARIOS
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USP_USUARIOS_D`(IN `IN_ID` INT)
DELETE FROM USUARIOS WHERE ID = IN_ID$$
DELIMITER ;