#Creacion procedimiento select ALUMNOS
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USP_ALUMNOS_R`(IN `IN_ID` INT)
SELECT A.ID, A.NOMBRE, A.PAPELLIDO, A.SAPELLIDO, A.TELEFONO, A.DNI, A.IDUSUARIO FROM ALUMNOS A WHERE A.ID = IN_ID$$
DELIMITER ;

#Creacion procedimiento select ALUMNOS
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USP_ALUMNOS_R_TODOS`()
SELECT A.ID, A.NOMBRE, A.PAPELLIDO, A.SAPELLIDO, A.TELEFONO, A.DNI, A.IDUSUARIO FROM ALUMNOS A$$
DELIMITER ;

#Creacion procedimiento select LIBROS
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USP_LIBROS_R`(IN `IN_ID` INT)
SELECT L.ID, L.TITULO, L.AUTOR, L.NUMPAGINAS, L.ESTADO, L.ISBN FROM LIBROS L WHERE L.ID = IN_ID$$
DELIMITER ;

#Creacion procedimiento select LIBROS
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USP_LIBROS_RTODOS`()
SELECT L.ID, L.TITULO, L.AUTOR, L.NUMPAGINAS, L.ESTADO, L.ISBN FROM LIBROS L$$
DELIMITER ;

#Creacion procedimiento select LIBROSDEALUMNO
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USP_LIBROSDEALUMNO_R`(IN `IN_ID` INT)
SELECT L.ID, L.IDALUMNO, L.IDLIBRO FROM LIBROSDEALUMNO L WHERE L.ID = IN_ID$$
DELIMITER ;

#Creacion procedimiento select USUARIOS
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USP_USUARIOS_R`(IN `IN_ID` INT)
SELECT U.ID, U.USUARIO, U.CONTRASENIA, U.ADMIN FROM USUARIOS U WHERE U.ID = IN_ID$$
DELIMITER ;